# Build and analyze WebGoat with ShiftLeft
name: ShiftLeft and Java WebGoat 

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Download ShiftLeft
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
      run: |
        export HOME=$GITHUB_WORKSPACE
        export TMPDIR=$HOME
        curl -O https://cdn.shiftleft.io/download/sl ; chmod a+x ./sl
        export branch_name=$( echo $GITHUB_REF | cut -d'/' -f3 )
        echo
        echo "The current directory is " $PWD
        echo
        echo "Base directory contents:"
        ls
        echo
        echo "Server directory contents: "
        ls webgoat-server
        echo
        echo "Server target directory contents:"
        ls webgoat-server/target
